sudo: required
services:
  - docker

before_install:
  - docker build -t myahiatene/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true myahiatene/react-test npm test

after_success:
  - docker build -t myahiatene/multi-client ./client
  - docker build -t myahiatene/multi-nginx ./nginx
  - docker build -t myahiatene/multi-server ./server
  - docker build -t myahiatene/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push myahiatene/multi-client
  - docker push myahiatene/multi-nginx
  - docker push myahiatene/multi-server
  - docker push myahiatene/multi-worker
